language: node_js
sudo: false
node_js:
- '11'
cache:
  directories:
  - node_modules/
deploy:
  provider: npm
  email: sebastian.ovide@gmail.com
  api_key:
    secure: cu/8D4I0WXMVE6mTZR1LG4WGslvFM3FHz8EvYYY7DfWMmWV3DDMiOMPW1YjhBSDGOeysphB1gR6r73bvzPlZZzE7CEmDWvJMKdUL7g0e7ivwLcoMKW6gzkUV6UONpuMPYnAKN6vg29c60OG7dCUAtKQM6VaZooZ+B9Tl6ncO1B/ZPbmDkETupZ8GqmtLfYJHyI4BoLxE/PjVsMdtfSsdy43OzaNX23aK8BGhgcdIsdwQ/ZXuOsUSYUqPnpxWKKWsuCkrDvzUO84MrVm7CXjfqfiixF9knItKE/m3Y9Zu829guUkV1567NlKfZ1bfEpC+kl6ZR68Tii6TPMeo0SMX/GJK3TZ9htcM2opYutf/EQRsAj1opE1hS24TNKCfpIy8m8PloYJdBkWzwgZqV2P8M6TFsmmwB/1HMZDV+eytUqT8pOvsA5tenclLPCKa8YHrTj+weXKDnpVwkKPG5RukKpDoXCnCxKrC3znAAVlM3AjgUS8aEEUVyxKg1sMdaO66fVO/sRWoZqB49I5zR2jI6l5kEwMkeAo6UCRVHEJTV7EymYGS009tDEIs95qkxrwF5gkIoU2ds7NM4xdg7hTINJ4JrdNpNC9/ZcdLMtiGou0u/b40h9z++1XDKlHDyOrZHNbhSRdIK21t0w6BU0fQUOlwrIC63QjoqLR6pFv4cqo=
  on:
    tags: true
    repo: Geovation/photos
