language: node_js
sudo: false
node_js:
- '10'
cache:
  directories:
  - node_modules

script:
  - npm test -- --coverage # Include coverage when running tests
  - npm run build

after_script: # Upload coverage reports
  - npm run coveralls # remember to st COVERALLS_REPO_TOKEN

deploy:
  provider: npm
  email: sebastian.ovide@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: true
