language: node_js
sudo: false
node_js:
- '11'
cache:
  directories:
  - node_modules/
deploy:
  provider: npm
  email: sebastian.ovide@gmail.com
  api_key:
    secure: e4XOm9mKQYKiYNauIZpvVkHhEAqLjrmfruie3S6562oalu0NFm91OyX0z82CvxIhCemtJEVe/Y0Ypo1XbvgAYiyg7QagmEiirecXoL6POVFNIwdULhO1sTN5jCvFubmMnHB1N/b73k1Q4OWtCnSdMFCaBMcWCwsRgqCIhhZTMolbP6+XMDoRNmDu8KLE0EhD7EXDOHzhaS5C1b6UnKjWHv0QSL0w9s8NrFO4mAFDu1rgSemNEY0KnjZLVZLk59tLbmKGJv31FQxDXER0mV68rh4qY7Q1Q0f3LqEEpNQJJUGSAvQ7OVZPaUoIFTxAeAjtR5SJLZShpQzDWR4kKQFthCpbkUDQFqZAXxp2d8Qj9bKmtB39zarm6hixqvUNEKTA5o1IzY+f7t8EgV4t6FMtSZ5IQETHYmc/OKE95eIAXI64L2VLXsp0kSSGXxG7UWgfN/rhQP7ht0gzZwli1ab99o7sClAzz0zWeDXTbFQZvYYhbjXjJ0KAIJfI/Kp+kgPOm6k9MFDlgD5epIkQG7j37kiIp5BdrIfl9NuyZbrjKCeRH2EwrAC2DYwN+7UgTiZqcKcSUOfbAdcOo3/y6Lke+4qTx/E5Ps7NvtBB0SOyxhBsmziz6wn9Z5Iz9ac7eaOQiy2njT+Lrqj5xl5zNcKlbm8BrZI2Psvcak7Wa9J1Dr0=
  on:
    tags: true
    repo: Geovation/photos
