language: node_js
sudo: false
node_js:
- '11'
cache:
  directories:
  - node_modules/
deploy:
  provider: npm
  email: sebastian.ovide@gmail.com
  api_key:
    secure: Gn7/A3amlzZHy5XGutDNSyHZnwIHyHrUK5VDloT1mfKqVMGwtSnwl63dyLiqhy08o2EyX8s20i3NJOUCtvIR6bl88QFnXcX/d5QXIC217Kuv5NrzEYpm1mT3M3UarhDY1yIp6JJ31sb0FLmptp14KuO0TgzXWAsNOGM4ZRWEkfpvxGZPUEN5C6NpO5To2UKrMbDZfqaZlkY39cEkb1j+wAPWqD6osnh8pNYXEAuysmbv0UmorRiCGInKNX/kfbNQYlDXDhICFVQb+dkaAETVwCnuw3F2YGLdF3YBDOo027opeRodlQs0wOTqYIsU/hizm0krxeuWeMiSzBKKA6qczMix+AC7449ZJhkl2P3tM0iuoUBWyjD15o2Ymdh1Qi2VcB8Lz6WDQhkts/Fw/NwfW/Zs9KZWoWidipMBeFF4O1Uccxwhw+ijL3dB9gDZrCjYyb63NXCY6D4wmFGE8/X8qtwsZjmVGfanG37Z9Rhk5M0RRIee+0qloEZpxbVjO5Bh++JM9dknrtMhS2TWdcOHowWbJdJ62ItqtHfGnaXREO31m7YuVNGWRhhlcfVvyai1zGHbOw18JLSF2Ej/sbxiAuiVIB/marANqrn0r34Ib1PY0TrMdjmXL5OmxTP4KbNmaZI47LfuoM4fJI+CmSVY1BZDLmy2NTr7kLc3k56m5l0=
  on:
    tags: true
    repo: Geovation/photos
