const styles = {
    'wrapper':{
      display:'flex',
      flex:1,
      flexDirection:'column',
      height:'100vh',
      backgroundColor:'#333'
    },
    'headline':{
      display:'flex',
      flex:1,
      flexDirection:'column',
      maxHeight:170,
      justifyContent:'center'
    },
    'headtext':{
      color:'white',
      alignSelf:'center',
      paddingTop:10,
      fontFamily: 'OSGillSans ,sans-serif !important'
    },
    'headphoto':{
      display:'flex',
      flex:1,
      maxHeight:80,
      alignSelf:'center',
      paddingBottom:10
    },
    'appbar':{
      display:'flex',
      flex:1,
      maxHeight:52,
      textAlign:'center',
      alignItems:'center',
      justifyContent:'flex-start',
      backgroundColor:'#faa728',
      paddingLeft:5
    },
    'buttonappbar':{
      height:25
    },
    'photoappbar':{
      alignSelf:'center'
    },
    'body':{
      display:'flex',
      flex:1,
      flexDirection:'column',
      backgroundColor:'#faa728'
    },
    'camera':{
      display:'flex',
      flex:1,
      flexDirection:'column',
      justifyContent:'center',
      alignSelf:'center',
      backgroundColor:'#faa728'
    },
    'inputcamera':{
      opacity: 0,
      height:50,
      width:'50px',
      position:'absolute',
      cursor: 'pointer'
    },
    'imagecamera':{
      height:50,
      cursor: 'pointer'
    },
    'map':{
      display:'flex',
      flex:1,
      justifyContent:'center',
      alignItems:'center'
    },
    'imagemap':{
      height:50
    },
    'wrapperexternallink':{
      display:'flex',
      flex:1,
      flexDirection:'column',
      justifyContent:'flex-end'
    },
    'externallink':{
      display:'flex',
      flex:1,
      maxHeight:50,
      justifyContent:'center',
      alignItems:'center',
      backgroundColor:'#333'
    },
    'buttonexternallink':{
      color:'#faa728'
    }
}

export default styles;
