const styles = {
    'wrapper':{
      display:'flex',
      flex:1,
      flexDirection:'column',
      height:'100vh',
      backgroundColor:'#333'
    },
    'headline':{
      display:'flex',
      height:50,
      backgroundColor:'#faa728',
      alignItems:'center'
    },
    'buttonback':{
      height:25
    },
    'entertext':{
      display:'flex',
      height:50,
      paddingLeft:5,
      color:'#faa728',
      alignItems:'center'
    },
    'inputtext':{
      marginLeft:'5px'
    },
    'picture':{
      display:'flex',
      flex:1,
      flexDirection:'column',
      alignItems:'center',
      justifyContent:'center'
    },
    'sendwrapper':{
      display:'flex',
      flexDirection:'column',
      justifyContent:'center',
      alignItems:'center',
      height:50
    },
    'sendbutton':{
      color:'#333',
      backgroundColor:'#faa728'
    }
}

export default styles;
