const styles = {
    'wrapper':{
      display:'flex',
      flex:1,
      flexDirection:'column',
      height:'100vh',
      backgroundColor:'#333'
    },
    'headline':{
      display:'flex',
      flex:1,
      maxHeight:50,
      backgroundColor:'#faa728',
      alignItems:'center'
    },
    'buttonback':{
      height:25
    },
    'headtext':{
      display:'flex',
      flex:1
    },
    'entertext':{
      display:'flex',
      flex:1,
      maxHeight:50,
      paddingLeft:5,
      color:'#faa728',
      alignItems:'center'
    },
    'inputtext':{
      marginLeft:'5px'
    },
    'body':{
      display:'flex',
      flex:1,
      flexDirection:'column',
      backgroundColor:'#faa728'
    },
    'sendwrapper':{
      display:'flex',
      flex:1,
      flexDirection:'column',
      alignItems:'center',
      justifyContent:'center'
    },
    'picture':{
      display:'flex',
    },
    'send':{
      display:'flex',
      flex:1,
      flexDirection:'column',
      justifyContent:'flex-end',
      height:50,
      paddingBottom:5
    },
    'sendbutton':{
      color:'#333',
      backgroundColor:'#faa728',
      marginBottom:'15px'
    }
}

export default styles;
