export const suggestions = [
  {
    label: 'Most Popular',
    options:[
      {label:'Portrait photography'},
      {label:'Street photography'},
      {label:'Genre art'},
      {label:'Conceptual photography'},
    ]
  },
  {
    label: 'All Categories',
    options:[
      {label:'Abstract photography'},
      {label:'ActionShot'},
      {label:'Aerial photography'},
      {label:'Analog photography'},
      {label:'Architectural photography'},
      {label:'Astrophotography'},
      {label:'Aviation photography'},
      {label:'Banquet photography'},
      {label:'Candid photography'},
      {label:'Close-up'},
      {label:'Conceptual photography'},
      {label:'Concert photography'},
      {label:'Conservation photography'},
      {label:'Documentary photography'},
      {label:'Event photography'},
      {label:'Fancy portrait'},
      {label:'Fashion photography'},
      {label:'Fauxtography'},
      {label:'Femto-photography'},
      {label:'Film still'},
      {label:'Fine-art photography'},
      {label:'Fire photography'},
      {label:'Fireworks photography'},
      {label:'Food photography'},
      {label:'Forensic photography'},
      {label:'Genre art'},
      {label:'Geophotography'},
      {label:'Glamour photography'},
      {label:'High key'},
      {label:'High-speed photography'},
      {label:'Humanist photography'},
      {label:'Imagery intelligence'},
      {label:'In-game photography'},
      {label:'International Society for Aviation Photography'},
      {label:'Kirlian photography'},
      {label:'Lifestyle photography'},
      {label:'Lo-fi photography'},
      {label:'Lomography'},
      {label:'Long-exposure photography'},
      {label:'Low key'},
      {label:'Low-key photography'},
      {label:'Macro photography'},
      {label:'Medical photography'},
      {label:'Monochrome photography'},
      {label:'Narrative photography'},
      {label:'Night photography'},
      {label:'Old-time photography'},
      {label:'Ontheroofs'},
      {label:'Panorama'},
      {label:'Panoramic photography'},
      {label:'Pellier Noir'},
      {label:'Photo op'},
      {label:'Photobiography'},
      {label:'Photography by indigenous peoples of the Americas'},
      {label:'Photojournalism'},
      {label:'Photovoice'},
      {label:'Photowalking'},
      {label:'Pictorialism'},
      {label:'Polaroid art'},
      {label:'Portrait photography'},
      {label:'Post-mortem photography'},
      {label:'Red shirt (photography)'},
      {label:'Rogues" gallery'},
      {label:'Satellite imagery'},
      {label:'Secret photography'},
      {label:'Slow photography'},
      {label:'Snapshot (photography)'},
      {label:'Snapshot aesthetic'},
      {label:'Social documentary photography'},
      {label:'Social photography'},
      {label:'Soft focus'},
      {label:'Star trail'},
      {label:'Still life photography'},
      {label:'Still photography'},
      {label:'Stock photography'},
      {label:'Straight photography'},
      {label:'Street photography'},
      {label:'Subminiature photography'},
      {label:'Tele-snaps'},
      {label:'The Straight Up'},
      {label:'Thoughtography'},
      {label:'Time-lapse photography'},
      {label:'Travel photography'},
      {label:'Ultraviolet photography'},
      {label:'Underwater videography'},
      {label:'Vernacular photography'},
      {label:'Vintage print'},
      {label:'Visual anthropology'},
    ]
  }
];
