# language: node_js
# sudo: false
# node_js:
#   - "14"
# cache:
#   directories:
#     - node_modules/

# script:
#   - npm test -- --coverage # Include coverage when running tests
#   - npm run build

# after_script: # Upload coverage reports
#   - npm run coveralls # remember to st COVERALLS_REPO_TOKEN

# before_deploy:
#   - pushd functions && npm install && popd
#   - npm run build

# deploy:
#   - provider: firebase
#     skip_cleanup: true
#     token: "$FIREBASE_TOKEN"
#   - provider: npm
#     email: sebastian.ovide@gmail.com
#     api_key: $NPM_TOKEN
#     on:
#       tags: true
# env:
#   global:
#     # "$FIREBASE_TOKEN"
#     secure: RJyCjaUK7FUg0JVEhKVXj8UAMt8McTkqi0Kb2nZVsiTu+H4ZqhEpAghiSl30s8c7dzus4DpDhk2aV/bb04AecZ6xeoDWFevIB0Vrd3ym/ezFBP/azuaNBrZW7yaUyNkuAD1PLZaBqMySZfZabyImMzFKcBZOh9iomlWKph5yzSWI/Fs13rNm61KAwiiGTIzew1zdaIFQsX7rRTPBFCzTYpQO1HyadZzacogIiwSy9FL2GLkFwxp2gf+yX2mjesmIGaNO7eImFH2YkPDoK6BogPjv+gFJBzywXds16NCzAIU+HMZxqEvxiL8mRboZ/LUnQfrN0FX3L9KMPn3bs7dZcJiEbTqtW3/RTBG/ZqVeyDL9KM7xcT9CSmbB9P4Ot3onNQFS/FsXtn3fTJH6E3qj8NdYD4CwbupJanqicTOw3Epb1zUxoU7FL4HUYPIz67pAW8ZIuS8/3EXn7pa0wgR9uaADdUQ6I3KPavH9n0Ddg1G9qqPpOef2PEyJnkdNkCbujAWimKks5cHvY+xdJQBtOUWi4G5TCjQYjGsN676wfhlvBKi3Ih8SCvzBiUFe75/y8T79AZe9Sjfdg0pr8fsE78MEs+yWdXKjpuaU03Vp2BAOR6NRzYL5JA94ZoAXLNfFnL0L9fOaKHff7ib7P2Kc07b9tr7Dwt5R70urKHSqya0=

# name: "build"
on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
  pull_request:
  release:
    types:
      - created

jobs:
  
  unit-test-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node_modules-
      - name: install npm packages
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm test -- --coverage
        #  - npm run coveralls # remember to st COVERALLS_REPO_TOKEN
      # upload react build
      - uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

  unit-test-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('functions/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node_modules-
      - name: install npm packages
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: cd functions && npm ci
      - run: cd functions && npm test
  
  unit-test-firebase:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node_modules-
      - name: install npm packages
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run test:firebase
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: firestore-coverage
      #     path: |
      #       firestore-coverage.html
      #       firestore-debug.log

  build:
    # Let build it anyway so we can still play with the build... it will not deploy
    # needs: [unit-test-web, unit-test-functions, unit-test-firebase, e2e-test-web]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # build react
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node_modules-
      - name: install npm packages
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci
      - run: npm run build

      # upload react build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  deploy:
    # if: github.event_name == 'release' && github.event.action == 'created'
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: "it releases the PWA, functions and security rules"
    needs: [build, unit-test-web, unit-test-functions, unit-test-firebase]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node_modules-
      - name: install npm packages
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm ci

      # get react build
      - name: Download a react build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      # - name: Deploy to Firebase
      #   uses: w9jds/firebase-action@master
      #   with:
      #     args: deploy -m "V${{ steps.package-version.outputs.version }}"
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      #     PROJECT_ID: photos-demo-d4b14 
      - run: npm run deploy
